Hexagonal Architecture PR 2차
silberbullet/nettee-backend-hexagonal-sample pull request #3
Opened 2024-12-15 09:54 UTC by silberbullet

@merge-simpson 님이 제안해주신 프로젝트 구조로 변경 하였습니다.

```
│  │  └─com
│  │      └─nettee
│  │          ├─board
│  │          │  ├─adapter
│  │          │  │  ├─in
│  │          │  │  │  ├─mapper
│  │          │  │  │  └─web
│  │          │  │  │      └─dto
│  │          │  │  └─out
│  │          │  │      └─persistence
│  │          │  │          ├─entity
│  │          │  │          └─mapper
│  │          │  └─application
│  │          │      ├─domain
│  │          │      ├─port
│  │          │      ├─service
│  │          │      └─usecase
│  │          └─common
```
### 🚀 구조 개선 후 다음과 같은 이점을 얻었습니다!

- 향 후 도메인 추가 작업 있을 시, 프로젝트의 응집도가 낮아집니다!
- 기존 application 영역의 도메인 엔터티가 [ application : domain , adapter : domainEntity ] 로 분리가 됨으로써 application 영역은 JPA 의존을 하지 않게 됐습니다. 
- update 메소드를 builder 패턴을 통해 구현함으로써 향후 컬럼 추가시에도 유지보수 측면에서 향상이 되었습니다!

2024-12-15 10:17 UTC, merge-simpson requested changes

2024-12-15 10:17 UTC, merge-simpson commented on src/main/java/com/nettee/board/adapter/out/persistence/BoardQueryAdapter.java
> +        return Optional.ofNullable(boardEntityMapper.toDomain(
만약 들여쓰기 뎁스를 조정하고 싶다면, `mapper.toDomain(...)` 결과를 **변수에 담아서** `Optional.ofNullable(변수)`로 반환하는 게 어떨까 합니다.

2024-12-15 10:17 UTC, merge-simpson commented on src/main/java/com/nettee/board/application/usecase/BoardReadUseCase.java
> +import java.util.List;
사용하지 않는 임포트 같습니다!

2024-12-15 10:17 UTC, merge-simpson commented on src/main/java/com/nettee/common/BaseTimeEntity.java
시간에는 타임스탬프 호환, 다른 시간 타입들과 호환이 잘되는 `java.time.Instant` 타입을 권합니다. 자바 8에 나온 타입입니다.

2024-12-15 11:00 UTC, silberbullet commented on src/main/java/com/nettee/board/application/usecase/BoardReadUseCase.java
> +import java.util.List;
수정 완료 하였습니다!

2024-12-15 11:21 UTC, silberbullet commented on src/main/java/com/nettee/board/adapter/out/persistence/BoardQueryAdapter.java
> +        return Optional.ofNullable(boardEntityMapper.toDomain(
```java
    default Optional<Board> toOptionalDomain(BoardEntity boardEntity) {
        return Optional.ofNullable(toDomain(boardEntity));
    }
```
Mapstruct는 기본적으로 Optional을 반환하지 않아 default 메서드를 통해 커스텀 로직을 처리 하였습니다.

2024-12-15 11:37 UTC, silberbullet commented on src/main/java/com/nettee/common/BaseTimeEntity.java
찾아보니 호환성도 있지만 LocalDateTime은 ZoneId에 따라 시간대를 다르게 봔환하네요.
-> ex) Seoul, Dokyo 각각 다르게 시간대 채택되기 때문에 시스템적인 시간을 사용한다면 Instant가 선택이 맞아보입니다!

2024-12-15 11:41 UTC, merged

2024-12-17 17:01 UTC, merge-simpson commented on src/main/java/com/nettee/common/BaseTimeEntity.java
네 ㅎㅎ 타임스탬프 호환이 방금 말씀하신 내용을 내포합니다. 자세히 풀어 쓰진 않았네요.

# Timestamp 선호

UTC(≈ GMT) 기준으로 타임스탬프를 사용하여, 타임존에 따른 번거로운 offset 조정을 생략하는 것을 서버에서의 기본 시간 취급 방식으로 합니다.

타임존에 따라서는 연중 시기에 따라 offset이 유동적인 지역도 있거든요.  
한국은 Asia/Seoul 타임존을 사용하고, 1년 365일 +0900으로 일정한 오프셋을 유지하지만,  
일부 국가는 계절 등에 따라 오프셋이 바뀔 수 있습니다.

그리고 실제 시간은 대부분 '사용자'의 시스템 시각에 따라 표현되도록  
클라이언트에서 오프셋을 계산하여 사용하는 것이 좋습니다.  
즉, 프론트엔드에서 처리한다고 생각하면 됩니다.

## Timestamp 타입을 선호하는 이유

1. 시간은 대부분 사용자 시각에 맞추기 (클라이언트에서 처리)
2. Offset 조정을 생략하여 훨씬 간결하고 편리한 관리

2024-12-17 17:12 UTC, merge-simpson commented on src/main/java/com/nettee/board/adapter/out/persistence/BoardQueryAdapter.java
> +        return Optional.ofNullable(boardEntityMapper.toDomain(
네, 코드 효율이 좋아 보입니다.

작성하신 코드가 좋습니다.

이미 생각하셨을 수도 있지만, 혹시나 도움이 될 수도 있어서  
아래 두 코드를 비교해서 왜 더 좋은지 설명을 붙이겠습니다.  
(Better 코드가 @silberbullet 님의 코드입니다.)

- ✅ Better 👍
  ```java
  default Optional<Board> toOptionalDomain(BoardEntity boardEntity) {
      return Optional.ofNullable(toDomain(boardEntity));
  }
  ```
  > 발견된 객체(3): BoardEntity 객체 1, Board 객체 1, Optional<Board> 객체 1
- ❌ Not good
  ```java
  default Optional<Board> toOptionalDomain(BoardEntity boardEntity) {
      // Optional<BoardEntity> 객체가 생깁니다.
      return Optional.ofNullable(boardEntity)
              // Optional<Board> 객체가 생깁니다.
              .map(this::toDomain);
  }
  ```
  > 발견된 객체(4): BoardEntity 객체 1, Board 객체 1, Optional<BoardEntity> 객체 1, Optional<Board> 객체 1

작성하신 방식은 Optional 객체가 하나만 생성되어 메모리 할당 비용을 최소화합니다.  
아래 방식은 옵셔널 객체를 총 두 개 생성하며, 그중 하나는 전혀 불필요합니다.  

`Optional` 클래스의 `map` 함수를 사용해야 한다는 강박에 빠지면 자주 나타나는 실수일 수 있어서 덧붙였습니다.